import React from 'react'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import draft from './fixtures/report_draft.json'
import final from './fixtures/report_final.json'
import versions from './fixtures/report_versions.json'

vi.mock('../api.js', async (importOriginal) => {
  const actual = await importOriginal()
  const names = ['listPatients', 'reportVersions', 'reportGenerate', 'reportGet', 'reportRefresh', 'reportFinalize']
  return { ...actual, downloadReport: vi.fn(), api: Object.fromEntries(names.map((n) => [n, vi.fn()])) }
})
import { api, downloadReport } from '../api.js'
import CaseReportPanel from '../components/CaseReportPanel.jsx'

beforeEach(() => {
  vi.clearAllMocks()
  api.listPatients.mockResolvedValue([{ patient_id: 'P1', name: 'Fx' }])
  api.reportVersions.mockResolvedValue([])
  api.reportGenerate.mockResolvedValue(draft)
  api.reportFinalize.mockResolvedValue(final)
  api.reportGet.mockResolvedValue(draft)
  downloadReport.mockResolvedValue(1234)
})

async function open() {
  render(<CaseReportPanel />)
  await userEvent.selectOptions(await screen.findByLabelText('Report case'), 'P1')
}

describe('Case clinical report', () => {
  it('generates only the selected sections and previews the server content with distinct states', async () => {
    await open()
    expect(await screen.findByTestId('report-versions')).toHaveTextContent(/No reports generated/)
    await userEvent.click(screen.getByLabelText('evidence'))
    await userEvent.click(screen.getByRole('button', { name: 'Generate new version' }))
    const box = await screen.findByTestId('report-preview')
    expect(api.reportGenerate.mock.calls[0][1]).not.toContain('evidence')
    expect(box.textContent).toMatch(/Patient summary/)
    expect(box.textContent).toMatch(/ATP7B/)
    expect(box.textContent).toMatch(/not a diagnosis/i)
  })

  it('downloads the backend PDF and JSON and finalizes a draft', async () => {
    await open()
    await userEvent.click(screen.getByRole('button', { name: 'Generate new version' }))
    await screen.findByTestId('report-preview')
    await userEvent.click(screen.getByRole('button', { name: 'Download PDF' }))
    await waitFor(() => expect(downloadReport).toHaveBeenCalledWith(draft.report_id, 'pdf'))
    expect(await screen.findByRole('status')).toHaveTextContent(/generated by the server/)
    await userEvent.click(screen.getByRole('button', { name: 'Finalize' }))
    await waitFor(() => expect(api.reportFinalize).toHaveBeenCalledWith(draft.report_id))
    await waitFor(() => expect(screen.queryByRole('button', { name: 'Finalize' })).toBeNull())
    expect(within(screen.getByTestId('report-preview')).getByText(/\(final\)/)).toBeTruthy()
  })

  it('shows backend errors and an integrity warning instead of success', async () => {
    api.reportGenerate.mockRejectedValue(new Error('Select at least one valid report section.'))
    await open()
    await userEvent.click(screen.getByRole('button', { name: 'Generate new version' }))
    expect((await screen.findByRole('alert')).textContent).toMatch(/Select at least one/)
    api.reportGenerate.mockResolvedValue({ ...draft, integrity_ok: false })
    await userEvent.click(screen.getByRole('button', { name: 'Generate new version' }))
    expect((await screen.findAllByRole('alert')).some((a) => /Integrity check failed/.test(a.textContent))).toBe(true)
  })
})
