import React, { useEffect, useState } from 'react'
import { api, downloadReport, consumeNavContext } from '../api.js'

const ALL = ['patient', 'phenotypes', 'variants', 'diagnosis', 'pedigree', 'pgx', 'reproductive', 'evidence']
const LABEL = { available: 'Available', not_documented: 'Not documented', not_analyzed: 'Not analyzed', insufficient: 'Insufficient data', no_result: 'No matching result' }

export default function CaseReportPanel() {
  const [patients, setPatients] = useState([])
  const [pid, setPid] = useState('')
  const [picked, setPicked] = useState(ALL)
  const [versions, setVersions] = useState([])
  const [report, setReport] = useState(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState(null)
  const [info, setInfo] = useState(null)

  useEffect(() => {
    const ctx = consumeNavContext('reports')
    api.listPatients().then((p) => { setPatients(Array.isArray(p) ? p : p?.patients || []); if (ctx?.patient_id) load(ctx.patient_id) }).catch(() => {})
  }, [])

  const guard = async (fn) => {
    setError(null); setInfo(null); setBusy(true)
    try { await fn() } catch (e) { setError(e.message) } finally { setBusy(false) }
  }
  const [quality, setQuality] = useState(null)
  const load = (id) => guard(async () => {
    setPid(id); setReport(null); setVersions([]); setQuality(null)
    if (id) {
      setVersions(await api.reportVersions(id))
      try { setQuality(await api.qualityCase(id)) } catch { setQuality(null) }
    }
  })
  const open = (id) => guard(async () => setReport(await api.reportGet(id)))
  const generate = () => guard(async () => {
    const r = await api.reportGenerate(pid, picked)
    setReport(r); setVersions(await api.reportVersions(pid))
  })
  const refresh = () => guard(async () => setReport(await api.reportRefresh(report.report_id)))
  const finalize = () => guard(async () => {
    setReport(await api.reportFinalize(report.report_id)); setVersions(await api.reportVersions(pid))
  })
  const dl = (kind) => guard(async () => { const n = await downloadReport(report.report_id, kind); setInfo(`Downloaded ${kind.toUpperCase()} (${n} bytes) generated by the server.`) })
  const toggle = (s) => setPicked((p) => (p.includes(s) ? p.filter((x) => x !== s) : [...p, s]))

  return (
    <section className="panel p-4 space-y-3" data-testid="case-report">
      <div>
        <h3 className="text-base font-bold text-on-surface">Case clinical report</h3>
        <p className="text-xs text-on-surface-variant">Assembled from the case data on the server. The preview, JSON export and PDF are rendered from the same stored version.</p>
      </div>
      {error && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 text-red-800 text-xs px-3 py-2">{error}</div>}
      {info && <div role="status" className="text-xs text-primary">{info}</div>}
      <label className="text-xs font-semibold block">Case
        <select aria-label="Report case" value={pid} onChange={(e) => load(e.target.value)} className="mt-1 block w-full max-w-sm rounded-lg border border-outline-variant p-2 text-sm font-normal">
          <option value="">No case selected</option>
          {patients.map((p) => <option key={p.patient_id} value={p.patient_id}>{p.patient_id}{p.name ? ` — ${p.name}` : ''}</option>)}
        </select>
      </label>
      {pid && quality && (
        <div data-testid="data-quality" className={`rounded-lg border p-3 text-xs ${quality.conflicts.length ? 'border-amber-300 bg-amber-50 text-amber-900' : 'border-outline-variant bg-surface-container-low text-on-surface-variant'}`}>
          <div className="font-semibold">Data quality: {quality.status}</div>
          {quality.conflicts.map((c, i) => <div key={i} role="alert">{c.message}</div>)}
          {quality.notes.map((n, i) => <div key={i}>{n.message}</div>)}
          {quality.missing.length > 0 && <div>Missing: {quality.missing.map((m) => `${m.domain} (${m.state})`).join('; ')}</div>}
        </div>
      )}
      {pid && (
        <>
          <fieldset className="flex flex-wrap gap-3 text-xs">
            <legend className="font-semibold mb-1">Sections</legend>
            {ALL.map((s) => <label key={s} className="flex items-center gap-1"><input type="checkbox" checked={picked.includes(s)} onChange={() => toggle(s)} />{s}</label>)}
          </fieldset>
          <button onClick={generate} disabled={busy || picked.length === 0} className="px-3 py-2 rounded-lg bg-primary text-white text-xs font-semibold disabled:opacity-50">Generate new version</button>
          <div data-testid="report-versions" className="text-xs">
            {versions.length === 0 ? <p className="text-on-surface-variant">No reports generated for this case yet.</p> : (
              <ul className="space-y-1">{versions.map((v) => (
                <li key={v.report_id}><button onClick={() => open(v.report_id)} className="text-primary underline">Version {v.version}</button> · {v.status} · {v.created_utc} · {v.created_by}</li>))}</ul>)}
          </div>
        </>
      )}
      {report && (
        <div data-testid="report-preview" className="rounded-lg border border-outline-variant/40 p-3 text-xs space-y-2">
          <div className="flex flex-wrap items-center gap-2">
            <b>{report.content.title}</b><span>Version {report.version}</span><span>({report.status})</span>
            {!report.integrity_ok && <span role="alert" className="text-red-700">Integrity check failed</span>}
          </div>
          {report.content.sections.map((s) => (
            <div key={s.id}>
              <div className="font-semibold">{s.title} <span className="font-normal text-outline">— {LABEL[s.status] || s.status}</span></div>
              {s.note && <p className="text-outline">{s.note}</p>}
              {s.rows?.length > 0 && (
                <table className="w-full">{s.columns && <thead><tr className="text-left text-on-surface-variant">{s.columns.map((c) => <th key={c}>{c}</th>)}</tr></thead>}
                  <tbody>{s.rows.map((row, i) => <tr key={i} className="border-t border-outline-variant/30">{row.map((c, j) => <td key={j} className="py-0.5 pr-2">{String(c)}</td>)}</tr>)}</tbody></table>)}
            </div>
          ))}
          <p className="text-outline">{report.content.disclaimer}</p>
          <div className="flex flex-wrap gap-2">
            <button onClick={() => dl('pdf')} className="px-3 py-1.5 rounded-lg border border-primary/30 text-primary font-semibold">Download PDF</button>
            <button onClick={() => dl('json')} className="px-3 py-1.5 rounded-lg border border-primary/30 text-primary font-semibold">Export JSON</button>
            {report.status === 'draft' && <>
              <button onClick={refresh} className="px-3 py-1.5 rounded-lg border border-primary/30 text-primary font-semibold">Refresh from case data</button>
              <button onClick={finalize} className="px-3 py-1.5 rounded-lg bg-primary text-white font-semibold">Finalize</button></>}
          </div>
        </div>
      )}
    </section>
  )
}
